trigger:
  branches:
    include:
      - main   # main branch push olduğunda tetiklenecek

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent build için

variables:
  IMAGE_NAME: 'fastapi-app'
  TAG: 'latest'

steps:
# 1️⃣ Kodları checkout et
- checkout: self

# 2️⃣ Docker imajını build et
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    repository: '$(IMAGE_NAME)'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(TAG)

# 3️⃣ (Opsiyonel) Docker imajını push etmek istiyorsan
# Docker Registry bilgilerini gir (örneğin Docker Hub veya ACR)
# - task: Docker@2
#   displayName: 'Push Docker Image'
#   inputs:
#     command: 'push'
#     repository: '$(IMAGE_NAME)'
#     tags: |
#       $(TAG)
#     containerRegistry: '<Registry Service Connection>'
